### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by y0grt** [Zegorax/OnlyOffice-Unlimited#1]
I applied the patch (entrypoint in my docker-compose) but nothing changed.
Needs further adjustments?

Thank you.

**Comment by Zegorax** [comment]
Which Docker image did you use ?

**Comment by y0grt** [comment]
image: onlyoffice/documentserver:latest

**Comment by Zegorax** [comment]
Maybe try with onlyoffice/documentserver-ie

**Comment by y0grt** [comment]
Same result.
Nextcloud 18.0.3 with nextcloud:fpm image.
.lic file seems to be correctly created.

**Comment by Zegorax** [comment]
Please post your docker-compose.yml

**Comment by y0grt** [comment]
Document server is behing a nginx reverse proxy to provide SSL.
I deleted all containers, volumes (including those binded directories) and images.
Docker downloaded them again, and still have the issue.

```
onlyoffice-document-server:
    image: onlyoffice/documentserver-ie:latest
    restart: always
    volumes:
      - /vol1/nextcloud/onlyoffice/document_data:/var/www/onlyoffice/Data
      - /vol1/nextcloud/onlyoffice/document_log:/var/log/onlyoffice
      - /vol1/nextcloud/onlyoffice/document_lib:/var/lib/onlyoffice
      - /vol1/nextcloud/onlyoffice/document_postgres:/var/lib/postgresql
    networks:
      - back-tier
    entrypoint: bash -c "wget https://raw.githubusercontent.com/Zegorax/OnlyOffice-Unlimited/master/install.sh && bash install.sh"

```
