### ISSUE TITLE
Invalid licence

### ISSUE THREAD

**Issue by VictorJosso** [Zegorax/OnlyOffice-Unlimited#5]
Hi,

Thanks for your work. 
I have an issue. I have set the entry point in my docker-compose.yml file as written in the readme, but when I try to edit a document I have the error `Your license has expired. Please update your license and refresh the page.`
Here is my docker-compose.yml file:
```
version: '3'

services:
  onlyoffice:
    image: onlyoffice/documentserver-ie:latest
    restart: unless-stopped
    entrypoint: bash -c "wget https://raw.githubusercontent.com/Zegorax/OnlyOffice-Unlimited/master/install.sh && bash install.sh"
    ports:
      - "8282:80"
```

Do you have an idea on what is going on?
