### ISSUE TITLE
non-docker installs

### ISSUE THREAD

**Issue by compumatter** [Zegorax/OnlyOffice-Unlimited#7]
We have Nextcloud OO installed without Docker.  Do you have a version for that?

**Comment by VictorJosso** [comment]
If you have the Nextcloud built-in onlyoffice server (which is no longer supported on new Nextcloud versions), my advice is to disable this built-in server, install Docker, and run the OO server patched with Docker compose. 
Note: make sure the OO version you run is compatible with this patch (see #4). For example, 

```
version: '2'

services:
  onlyoffice:
    image: onlyoffice/documentserver-ie:5.5.0.165
    restart: unless-stopped
    entrypoint: bash -c "wget https://raw.githubusercontent.com/Zegorax/OnlyOffice-Unlimited/master/install.sh && bash install.sh"
    ports:
      - "8282:80"
```

Edit: you can run OO server on another device if yours is not supported by Docker (Raspberry pi...)
